# Generated by Django 2.2.3 on 2021-04-06 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_usuario', '0002_auto_20210331_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydelivery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
