# Generated by Django 2.2.3 on 2021-04-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_usuario', '0003_moneydelivery_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDeliveryLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('origin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_delivery_lock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
